sudo: required
services:
  - postgresql
addons:
  postgresql: "10.5"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
script:
- ./scripts/cibuild.sh