version: '3'

services:
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "python3",  "manage.py",  "runserver",  "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
