# Generated by Django 2.1.2 on 2018-10-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_auto_20181018_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
