# Generated by Django 2.1.2 on 2018-11-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_and_time', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('artist', models.ManyToManyField(to='bands.Artist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.Venue')),
            ],
        ),
    ]
