# Generated by Django 2.1.2 on 2018-11-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='artist',
            new_name='artists',
        ),
    ]
