# Generated by Django 2.1.2 on 2018-11-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_auto_20181104_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'artist', 'verbose_name_plural': 'artists'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'venue', 'verbose_name_plural': 'venues'},
        ),
    ]
