# Generated by Django 2.1.2 on 2018-11-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_auto_20181111_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
