# Generated by Django 2.1.2 on 2018-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_artist_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
