# Generated by Django 2.1.2 on 2018-11-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0013_user_favorite_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_venues',
            field=models.ManyToManyField(to='bands.Venue'),
        ),
    ]
