# Generated by Django 2.1.2 on 2018-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0014_user_favorite_venues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, to='bands.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_venues',
            field=models.ManyToManyField(blank=True, to='bands.Venue'),
        ),
    ]
